### ISSUE TITLE
Error in calculating the position of tooltips synced graphs

### ISSUE THREAD

**Issue by PavelMoore** [gravity-ui/yagr#195] opened 2023-12-22 08:20 UTC
If synced graphs have ordinate values that differ by an order of magnitude or more, the tooltip of one of the graphs may "fly" outside of this graph. Probably, the position of the first tooltip is calculated directly from the position of the second tooltip, not relatively. I can't fix it with config.

Live example: https://codepen.io/Pavel_Moore/pen/OJqJWwE
Screencast: https://disk.yandex.ru/i/pUo_qoaGdGplUA

**Comment by zefirka** [comment] 2023-12-25 10:05
I guess the problem is in tooltip, which was updated to handle multiple behaviours, so we could brake something. I'll fix it

**Comment by zefirka** [comment] 2023-12-25 12:50
Fixed in `4.0.4`

**Closed by zefirka** 2023-12-25 12:50 UTC
